version: '3.3'
services:

  gps-frontend:
    image: rafaelpcustodio/gps-frontend
    container_name: gps-frontend
    volumes:
      - '/app/node_modules'
    environment:
      - REACT_APP_GOOGLE_API_KEY=
      - REACT_APP_ENVIRONMENT=local
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
    stdin_open: true